include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_const_constructors: true
    always_put_required_named_parameters_first: true
    implementation_imports: true
    public_member_api_docs: true