import 'package:winter/src/i18n/messages.g.dart';
import 'package:winter/winter.dart';

export 'package:winter/src/i18n/messages.g.dart' show WinterMessages;

/// Messages of Winter for [locale], generated by slang from `lib/src/i18n/*.i18n.yaml`.
/// A language without YAML falls back to English (the base locale).
///
/// {@category i18n}
WinterMessages winterMessages(WinterLocale locale) =>
    _cache[AppLocaleUtils.parseLocaleParts(
      languageCode: locale.languageCode,
      countryCode: locale.countryCode,
    )]!;

final Map<WinterMessagesLocale, WinterMessages> _cache = {
  for (final l in WinterMessagesLocale.values) l: l.buildSync(),
};

/// The languages of [config] (supported and fallback) that Winter can't translate:
/// its validation messages fall back to English for them. A region counts as its language
/// (`es-MX` has the messages of `es`). One locale per language, in the order of [config].
///
/// {@category i18n}
List<WinterLocale> localesWithoutWinterMessages(LocaleConfig config) {
  final Set<String> translated = {
    for (final l in WinterMessagesLocale.values) l.languageCode,
  };
  final Set<String> seen = {};
  return [
    for (final l in [...config.supported, config.fallback])
      if (!translated.contains(l.languageCode) && seen.add(l.languageCode)) l,
  ];
}

/// Warn about the languages of [config] that Winter can't translate (see [localesWithoutWinterMessages]),
/// so a response that mixes the texts of the app (ex: French) and of Winter (English) is not a surprise.
///
/// {@category i18n}
void warnLocalesWithoutWinterMessages(LocaleConfig config) {
  final List<WinterLocale> missing = localesWithoutWinterMessages(config);
  if (missing.isEmpty) return;

  logger.warning(
    'Winter has no validation messages for ${missing.join(', ')}: '
    'they will be in English. Pass a custom `message:` to the validators.',
  );
}
