import 'package:winter/src/i18n/messages.g.dart';
import 'package:winter/winter.dart';

export 'package:winter/src/i18n/messages.g.dart' show WinterMessages;

/// Messages of Winter for [locale], generated by slang from `lib/src/i18n/*.arb`.
/// A language without ARB falls back to English (the base locale).
WinterMessages winterMessages(WinterLocale locale) =>
    _cache[AppLocaleUtils.parseLocaleParts(
      languageCode: locale.languageCode,
      countryCode: locale.countryCode,
    )]!;

final Map<WinterMessagesLocale, WinterMessages> _cache = {
  for (final l in WinterMessagesLocale.values) l: l.buildSync(),
};
